server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esto evita el 404 de React Router al recargar
        try_files $uri $uri/ /index.html;
    }

    # Esto redirige las peticiones de datos de React hacia tu API en Express
    location /api/ {
        proxy_pass http://backend:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}